// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { TelemetryArgs } from "./telemetry";
export type Telemetry = import("./telemetry").Telemetry;
export const Telemetry: typeof import("./telemetry").Telemetry = null as any;
utilities.lazyLoad(exports, ["Telemetry"], () => require("./telemetry"));

export { TelemetryListArgs } from "./telemetryList";
export type TelemetryList = import("./telemetryList").TelemetryList;
export const TelemetryList: typeof import("./telemetryList").TelemetryList = null as any;
utilities.lazyLoad(exports, ["TelemetryList"], () => require("./telemetryList"));

export { TelemetryPatchArgs } from "./telemetryPatch";
export type TelemetryPatch = import("./telemetryPatch").TelemetryPatch;
export const TelemetryPatch: typeof import("./telemetryPatch").TelemetryPatch = null as any;
utilities.lazyLoad(exports, ["TelemetryPatch"], () => require("./telemetryPatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:telemetry.istio.io/v1:Telemetry":
                return new Telemetry(name, <any>undefined, { urn })
            case "kubernetes:telemetry.istio.io/v1:TelemetryList":
                return new TelemetryList(name, <any>undefined, { urn })
            case "kubernetes:telemetry.istio.io/v1:TelemetryPatch":
                return new TelemetryPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("istio-pulumi", "telemetry.istio.io/v1", _module)
